name: boxx
description: Versioned Flutter key-value storage with authenticated encryption and change streams.
version: 0.3.0
homepage: https://github.com/Yoda-Man/box
repository: https://github.com/Yoda-Man/box
issue_tracker: https://github.com/Yoda-Man/box/issues

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  crypto: ^3.0.7
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  idb_shim: ^2.9.7
  path: ^1.9.1
  path_provider: ^2.1.6
  pointycastle: ^3.9.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
