name: boxx
description: Boxx is your ultimate key-value storage plugin with built-in encryption
version: 0.1.4
homepage: https://github.com/Yoda-Man/box

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  idb_shim: ^2.6.7
  path_provider: ^2.1.5
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

