name: boxx
description: Boxx is a lightweight and blazing fast key-value database written in pure Dart
version: 0.0.6
homepage: https://github.com/Yoda-Man/box

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  indexed_db: ^1.0.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

